import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import Image from 'next/image'
import calebImage from '../public/caleb.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Caleb Voorhees Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="divide-y-4 min-h-screen">
          <nav className ="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">Developer Portfolio</h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
                </li>
                <li>
                  <a 
                  className="bg-gradient-to-r from-blue-800 to bg-blue-500 text-white px-4 py-2 rounded-md ml-8" 
                  href="#"
                  >
                    Resume
                  </a>
                </li>
              </ul>
          </nav>
          <div className="p-1 relative mx-auto bg-gradient-to-bl from-blue-700 rounded-full w-48 h-48 mt-10 overflow-hidden">
            <Image src={calebImage} />
          </div>
          <div className="text-center p-5">
            <h2 className="text-5xl py-2 text-blue-600 font-medium">Caleb Voorhees</h2>
            <h3 className="text-2xl py-2">Junior Developer </h3>
            <p className="text-md py-3 leading-8 text-gray-800">
            I am a spring 2023 graduate of the Seton Hill University computer science program seeking an entry level development position that fits my skill set
            </p>
          </div>
          <div className="text-6xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
        </section>

        <section>
          <div className="text-center">
            <h3 className="text-3xl py-7">Potfolio Projects</h3>
            <p className="text-lg">
              Axel's Adventure 2D Platformer Video Game
            </p>
            <p className=" text-md py-3 text-gray-600 leading-8">
            Personal research project that helped me learn the basics of the Unity engine and scripting in C#
            </p>
          </div>
        </section>
      </main>
    </div>
  )
}
